### PR TITLE
Making necessary changes and adding Readme.md. please merge my pull request...

### PR DESCRIPTION
**Pull request by w3dg**
Removed `import package com.codepumpkin.boardGames;` and edited name of authors and added readme.md

### CODE REVIEW

**Comment by w3dg** [comment]
Please merge the pull request I have resolved the conflicts...
specialty benedicts

**Comment by w3dg** [comment]
Thank you for doing this favor.....

**Comment by DB03-biology** [comment]
Hi man!!!
After a long time gmailing...
Only a few days for our exam to end
Thinking about the next plans
O i remember.... it's puja....
So our test will over and enjoyment will start....
Ok bye.....i am getting late...i have to study history....

**Comment by w3dg** [comment]
### This is not a place to chat BTW

**Pull request merged**
